Publishing test results

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,13 +32,24 @@ jobs:
         run: npm run ci
 
       - name: Install playwright
-        run: npx playwright install --with-deps
+        run: cd frontend && npx playwright install --with-deps
 
       - name: Run tests
-        run: npm test
+        run: npm run test:ci
 
       - name: Build
         run: npm run build
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test Results
+          path: |
+            backend/backend-test-results.xml
+            frontend/frontend-unit-test-results.xml
+            frontend/frontend-e2e-test-results.xml
+          reporter: jest-junit        # Format of test results
 
       - name: Create Release
         if: startsWith(github.ref, 'refs/tags/')
